[project]
name = "biasvariancetradeoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "scikit-learn>=1.8.0",
]
