[project]
name = "graphs-mlpractitioner"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "seaborn>=0.13.2",
]
