[project]
name = "hyperparametertuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
]
