[project]
name = "marshmallowschematest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "marshmallow-dataclass>=8.7.1",
    "pyyaml>=6.0.3",
]
